# See https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
name: analyze

on:
  push:
    branches: ['main', 'maintenance/*']
    paths: ['.github/**', '.mvn/**', 'src/**', 'eclipse-formatter-config.xml', 'pom.xml']
  pull_request:
    branches: ['main', 'maintenance/*']
    paths: ['.github/**', '.mvn/**', 'src/**', 'eclipse-formatter-config.xml', 'pom.xml']
  schedule:
    - cron: '0 0 * * 6'

permissions:
  contents: 'read'
  pull-requests: 'write' # Required by SonarCloud to comment PRs
  security-events: 'write' # Required by all codeql-action workflows

jobs:
  sonar:
    # This workflow is only of value to the marcwrobel/jbanking repository and would always fail in forks
    if: github.repository == 'marcwrobel/jbanking'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: 'actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c'
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of sonar analysis

      - name: Set up Java
        uses: 'actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b'
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Cache SonarQube packages
        uses: 'actions/cache@4723a57e26efda3a62cbde1812113b730952852d'
        with:
          path: '~/.sonar/cache'
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: 'actions/cache@4723a57e26efda3a62cbde1812113b730952852d'
        with:
          path: '~/.m2/repository'
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
        run: 'mvn --settings .mvn/settings.xml -B -P analyze verify sonar:sonar'

  codeql:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout repository
        uses: 'actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c'
        with:
          # We must fetch at least the immediate parents so that if this is a pull request then we can check out the head.
          fetch-depth: 2

      - name: Initialize CodeQL
        uses: 'github/codeql-action/init@959cbb7472c4d4ad70cdfe6f4976053fe48ab394'
        with:
          languages: 'java'
          queries: 'security-and-quality'

      - name: Autobuild
        uses: 'github/codeql-action/autobuild@959cbb7472c4d4ad70cdfe6f4976053fe48ab394'

      - name: Perform CodeQL Analysis
        uses: 'github/codeql-action/analyze@959cbb7472c4d4ad70cdfe6f4976053fe48ab394'
