# See https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
name: analyze

on:
  push:
    branches: ['main']
  schedule:
    - cron: '0 0 * * 6'

permissions:
  contents: 'read'

jobs:
  sonar:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: 'actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8' # v3.1.0

      - name: Unshallow repository
        run:  'git fetch --prune --unshallow' # needed for sonar analysis

      - name: Set up Java
        uses: 'actions/setup-java@de1bb2b0c5634f0fc4438d7aa9944e68f9bf86cc' # v3.6.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
        run: 'mvn --settings .mvn/settings.xml -B -P analyze verify sonar:sonar'
