# See https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
name: analyze

on: ['push']

permissions:
  contents: 'read'

jobs:
  sonar:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: 'actions/checkout@v2'

      - name: Unshallow repository
        run:  'git fetch --prune --unshallow' # needed for sonar analysis

      - name: Set up Java 11
        uses: 'actions/setup-java@v1'
        with:
          java-version: '11'

      - name: Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
        run: 'mvn --settings .mvn/settings.xml -B -P analyze verify sonar:sonar'
